### ISSUE TITLE
PageEdit reports "Error on line1 at column1: Document is empty"

### ISSUE THREAD

**Issue by JohnParten** [Sigil-Ebook/PageEdit#14]
When submitting my epub to PageEdit, the document is not displayed and there is no helpful info. So I resorted to generating the simplest epub as follows using Sigil 1.1.0 (This is a Linux Fedora 31 environment with Sigil and Pagedit built from source) ...

Step 1) Open Sigil with no epub and select "Tools ->Restructure EPUB to Sigil Norm" (I tried without this step and got same result)
Step 2) Adjust Section0001.xhtml as attached in zip file
Step 3) Tools->Generate TOC
Step 4) Adjusted content.opf so dc:title was populated with a short title
Step 5) Save as "test.epub"
Step 6) ./pageedit ~/EPUB-TEST/test.epub
... a pink box appears with small writing "Error on line 1 column1: Document is empty"

[Section0001.zip](https://github.com/Sigil-Ebook/PageEdit/files/4232902/Section0001.zip)

I must be doing something silly but it is not immediately obvious to me

**Comment by kevinhendricks** [comment]
@JohnParten,
I think you misunderstand what PageEdit is and what it does.
PageEdit does not directly edit epub files.

Try the following:
1. Open up Sigil and go to Preferences and set PageEdit to be your Preferred XHtml editor.
2. open any epub in Sigil
3. In Sigil's BookBrowser, open up the opf file (often named content.opf) by double-clicking on it.
4. Sigil will open the opf file in its CodeView
5. Hit the pencil icon on Sigil to pass the opf list to PageEdit

And PageEdit should show you a list of xhtml files in spine order so that you can make simple edits, do proofing etc.

Any changes you save in PageEdit will appear in Sigil upon exiting PageEdit.

PageEdit can also be used outside of Sigil if you have standalone xhtml files, or manually unzip the epub, or use Sigil's FolderOut plugin to create a copy of the epub.

In that case, simply navigate to any of the unzipped xhtml files or the opf file itself in PageEdit and load it.

Hope this helps.

**Comment by JohnParten** [comment]
Oooohps ~ yes I have misunderstood ~ I thought PageEdit was a standalone epub reader. So what you say makes sense.Thankyou once again for a timely response. I followed your instructions and PageEdit now comes up when I select the pencil icon. I need to checkout the differences between the Sigil Preview Pane and PageEdit. Thanks for your help ~ Closing Ticket ~ JP
