### ISSUE TITLE
[Feature Request] Support for MathML

### ISSUE THREAD

**Issue by firstrose** [Sigil-Ebook/PageEdit#32]
![LdNNOCtz4z](https://github.com/Sigil-Ebook/PageEdit/assets/1551595/b690e53c-0eb1-44a3-aded-e4b06a306619)

**Comment by kevinhendricks** [comment]
Sorry but since PageEdit actually live edits the DOM tree, and MathML uses MathJax which is javascript to replace the mathml DOM nodes with svg, there can be no mathml support in PageEdit.

After MathMax runs you would be left with a bunch of SVG and no mathml to speak of.

Sorry, libpve efiting and javascripts that modify the tree do not work well together.

**Comment by kevinhendricks** [comment]
The latest Qt versions now natively support a limited set of mathml so Preview being a Qt app has now inherited that capabilitu
