### ISSUE TITLE
[Feature Request] Support for Search and Replacement

### ISSUE THREAD

**Issue by abtxu** [Sigil-Ebook/PageEdit#33]
Or is there any walk arround to achieve search and replacement?

**Comment by kevinhendricks** [comment]
We do not accept feature requests in our github issues.  Please post them to our Digil User's Forum on Mobileread so that other vested users can see and comment.
www.mobileread.com

Search already exists, but replacement is the harder part in PageEdit.  PageEdit was designed to work with Sigil which has extensive search and replace features.
