### ISSUE TITLE
PageEdit fail to insert an existing image/video/audio file properly from Sigil

### ISSUE THREAD

**Issue by coder168** [Sigil-Ebook/PageEdit#38]
When insert an existing image/video/audio by the button "insert an exisitng image video audio file", PageEdit can insert the selected file, but the resulted image link does not work properly, their "src" attributes point to invalid values, eg:
```html
 <img alt="image name" src="////////////////////////"/>
 <audio controls="controls" src="////////////////////////////////////////"></audio>
 <video controls="controls" src="///////////////////////////////////"></video>
```
Sigil has an similar button, it works fine, the resulted image/video/audio links point to the correct files selected and works properly. 
It is little annoying that you have to switch back and forth between Sigil and PageEdit for properly file insertion.

**Comment by kevinhendricks** [comment]
Okay I see, you did give me specific urls. 

Here is some debug output:

Debug: currentpath:  "/Users/kbhend/Desktop/test/OEBPS/Text/about_epub.xhtml"
Debug: mediapath:  "/Users/kbhend/Desktop/test/OEBPS/Images/ui_toc-tabbed.png"
Debug: mkind:  "image"
Debug: relative_link:  "../Images/ui_toc-tabbed.png"
Debug: after URLEncoding:  "???????????????????????????"

 For some reason the The URLEncodedPath when passed in a normal relative path is coming back with complete garbage.  That must be due to some change possibly by Qt.

I will try to track that down and get a fix in place for the next release.

**Comment by kevinhendricks** [comment]
Yes, the URLEncodePath routine got stepped on when we merged in Qt6 support by mistake.  It has now been fixed and the push fixed to PaegEdit master.

This fix will be included in our next release.

If you build your own from source, feel free to use PageEdit to get the fix now as PageEdit code is otherwise quite stable.

**Comment by kevinhendricks** [comment]
FYI, if are willing to test a pre-release CI build please let me know your platform and I can post one for you to download and use.

**Comment by coder168** [comment]
Thank @kevinhendricks for lighting fast support! 👍  👏 ㊗️ 

I am OK to waiting for the next official release.
