### ISSUE TITLE
PageEdit crashed without warning

### ISSUE THREAD

**Issue by KaijuKoder2** [Sigil-Ebook/PageEdit#42]
On Windows 11, entering into PageEdit. After 15 or so minutes of typing, PageEdit crashed without warning. No error message. No autosave either. Typing lost. Aside from stability issues, should really have an autosave.

**Comment by dougmassay** [comment]
Autosave is a non-starter. We won't be doing that. Conversations on why abound in many historical Sigil topics.

But crashing is always bad. How was PageEdit launched? From within Sigil, or on its own?

**Comment by kevinhendricks** [comment]
And the exact steps to recreate the crash would help.  As would version info, where downloaded from, etc.

**Comment by kevinhendricks** [comment]
Also, if it actually crashed, Windows would at least report something about the terminating event.  So could it have just hung?  Did the app itself disappear?  Or did you just get the non-responsive indicator based on the Windows os timer?

Have been pounding away entering gibberish text on my Windows 11 vm in PageEdit with no issues or crashes so I can not recreate what you are seeing.

**Comment by kevinhendricks** [comment]
It has now been running for 2 hours of nonsense typing and editing of an epub with no crashes or issues of any kind.  This is with PageEdit-2.3.1 dowloaded and installed from our Releases page of github.  This is with an up to date Windows 11.

So I can NOT recreate what you are seeing, which leads me to believe that you have conflicting system software installed on your computer (probably using an older version of Qt used in a non-Windows system extension or vendor specific tool.).

So without more information about how to recreate the issue, I believe this is a error  specific only to your system's configuration and will close this issue as works for me unless you can supply information from which we can recreate a crash, and that you have tried a safe boot and are still seeing the problem.

**Comment by KaijuKoder2** [comment]
It was a brand new Windows 11 PC arrived yesterday, installed  the latest Windows Update, then Sigil and PageEdit yesterday fresh from the Sigil website. Editing was made from PageEdit via Sigil in which we'd set preferences to use PageEdit as the external editor. Opened it on an EPUB (created on Windows 10 Sigil/PageEdit), typed for 15 minutes without saving (our mistake - should have been ctrl-s'ing as we went) when it crashed suddenly. As in, just stopped working. Went back to the desktop. We weren't doing anything unusual. Just typing.

Prior to that had been using Sigil/PageEdit on Windows 10, set up the same, for years without crashing. No problems at all. So obviously caused by something new.

Autosave is really useful in cases such as this, but sounds like you've already discussed it and concluded it's not feasible. 
For the time being we'll type in Libre and paste into PageEdit. You can close this if you like, and reopen it if anyone else encounters it. Thanks for investigating.

**Comment by kevinhendricks** [comment]
Interesting...  no crash but the code went out into weeds and created a hang.  If you rule out hardware issues and If this is a clean install in a new PC you can bet that your PC vendor has added its own system tools on top of pure Microsoft Windows.  Almost all PC vendors do this.  Unfortunately some of these vendors supplied tools are very broken in that they use  older Qt versions but do not strip out symbols and so these older versions get linked into modern Qt programs because they are in the memory space first.

Calibre has run into these types of problems so often they have tried to create a list of these broken vendor supplied Windows extras.

I will see if I can find that list and post a link to it here.

**Comment by kevinhendricks** [comment]
Here is what I found:  There are more "conflicting" programs on Windows than I thought:

https://manual.calibre-ebook.com/faq.html#calibre-freezes-crashes-occasionally

**Comment by KaijuKoder2** [comment]
Used Geek Uninstaller to look for bloatware. https://geekuninstaller.com/download Only found Norton. 

Think the only other Qt application on the system is LibreOffice. It did crash too (though a different error - segmentation violation or such) and restarted itself, to the point didn't even notice - discovered that in EventViewer. LibreOffice is prone to occasional crashes though even under Windows 10.

Did Google around and found Qt hangs are a thing (Qt takes too long to return from an operation, doesn't respond to Windows messages quickly enough to Windows, which assumes it has hung and terminates the process. In which case, PageEdit didn't actually crash) and that it's a particular problem with Windows 11. Google "windows 11 hanging". In which case, safe to assume it's a wider problem so happy to copy/paste from Libre into PageEdit for the time being. If it repeats under those conditions, will report it.

Thanks for investigating.

**Comment by dougmassay** [comment]
You might try exempting PageEdit's (and Sigil's) program and/or preference directory from Norton's  live scanning. I always do this with Sigil on any Windows system I install it on. I actually don't recommend running any third-party antivirus live scanners on Windows anymore. I've had nothing but problems when third-party AV systems try to coexist with Windows Defender.

I'm not here tell people how to run their systems, but I've simply not seen a need for Norton, or McAfee, and such since MS included Defender. I've only seen problems.

**Comment by kevinhendricks** [comment]
Agreed about removing or disabling Norton.  Norton decides to open and scan temporary files and that can cause io and file read delays and failures.  

Either way, I am going to close this.  We will reopen it if needed if more information becomes available.

**Comment by KaijuKoder2** [comment]
Thanks @dougmassay and @kevinhendricks. I already removed Norton before I installed Sigil/PageEdit. Because, Norton! :-)

I'll post if there's a repeat.
